### PR TITLE
New bookshelf textures at default resolution

### PR DESCRIPTION
**Pull request by KnightMiner**
Picture

As requested, no frames are included. #ChiselTextureOff

### CODE REVIEW

**Comment by alexbegt** [comment]
I do not approve this! Needs more textures!

**Comment by Drullkus** [comment]
Bottom shelf of abandoned is missing stuff, wanna fix? :)

**Comment by KnightMiner** [comment]
Updated picture

Updated PR with tweaked abandoned bookshelves

**Comment by Drullkus** [comment]
👍

**Pull request merged**
